export const conf = {
	BASE_URL: process.env.NEXT_PUBLIC_BASE_URL,
	ORG_NAME: process.env.NEXT_PUBLIC_ORGANIZATION_NAME,
	PROJECT_NAME: process.env.NEXT_PUBLIC_PROJECT_NAME,
	API_BASE_URL: process.env.NEXT_PUBLIC_BACKEND_API_BASE_URL,
	HOTJAR_ID: process.env.NEXT_PUBLIC_HOTJAR_ID,
	AMPLITUDEANALYTICS_TOKEN: process.env.NEXT_PUBLIC_AMPLITUDEANALYTICS_TOKEN,
	PROPERTY_ID: process.env.NEXT_PUBLIC_TAWK_PROPERTY_ID,
	WEIGHT_ID: process.env.NEXT_PUBLIC_TAWK_WEIGHT_ID,
	DISCORD_CDN: process.env.NEXT_PUBLIC_DISCORD_CDN,
	GITBOOK_URL: process.env.NEXT_PUBLIC_GITBOOK_URL,
	PROJECT_ID: process.env.NEXT_PUBLIC_PROJECT_ID,
	APP_DEVELOPER_PUBLIC_ADDRESS:
		process.env.NEXT_PUBLIC_APP_DEVELOPER_PUBLIC_ADDRESS,
	IS_MAINNET: process.env.NEXT_PUBLIC_IS_MAINNET,
	TELEGRAM_BOT_USERNAME: process.env.NEXT_PUBLIC_TELEGRAM_BOT_USERNAME,
};

console.log(`conf: ${JSON.stringify(conf)}`);

export const PREMIUM_GUILDS = [
	"732892373507375164", // fuel
	"915914985140531240", // rndao
	"980858613587382322",
	"1007641784798691468",
];
